//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bars.Gkh.Overhaul.Hmao.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bars.Gkh.Overhaul.Hmao.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ActualizeVersionLogReport {
            get {
                object obj = ResourceManager.GetObject("ActualizeVersionLogReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CertificationControlValues {
            get {
                object obj = ResourceManager.GetObject("CertificationControlValues", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CertificationControlValuesWithQuality {
            get {
                object obj = ResourceManager.GetObject("CertificationControlValuesWithQuality", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ControlCertificationOfBuild {
            get {
                object obj = ResourceManager.GetObject("ControlCertificationOfBuild", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountCeoByMuInPeriod {
            get {
                object obj = ResourceManager.GetObject("CountCeoByMuInPeriod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountRoByCeoInPublProgram {
            get {
                object obj = ResourceManager.GetObject("CountRoByCeoInPublProgram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountRoByMuInPeriod {
            get {
                object obj = ResourceManager.GetObject("CountRoByMuInPeriod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CrShortTermPlan {
            get {
                object obj = ResourceManager.GetObject("CrShortTermPlan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CtrlCertOfBuildConsiderMissingCeo {
            get {
                object obj = ResourceManager.GetObject("CtrlCertOfBuildConsiderMissingCeo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CtrlFillDataForFormLongProg {
            get {
                object obj = ResourceManager.GetObject("CtrlFillDataForFormLongProg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DpkrDataAnalysisReport {
            get {
                object obj = ResourceManager.GetObject("DpkrDataAnalysisReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DpkrGroupedByPeriod {
            get {
                object obj = ResourceManager.GetObject("DpkrGroupedByPeriod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DpkrGroupedByPeriodPublish {
            get {
                object obj = ResourceManager.GetObject("DpkrGroupedByPeriodPublish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FinanceModelDpkr {
            get {
                object obj = ResourceManager.GetObject("FinanceModelDpkr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FormFundNotSetMkdInfo {
            get {
                object obj = ResourceManager.GetObject("FormFundNotSetMkdInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HouseInformation {
            get {
                object obj = ResourceManager.GetObject("HouseInformation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HousesExcessMargSum {
            get {
                object obj = ResourceManager.GetObject("HousesExcessMargSum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HousesHaveNotCollectSum {
            get {
                object obj = ResourceManager.GetObject("HousesHaveNotCollectSum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ImportedDpkrReport {
            get {
                object obj = ResourceManager.GetObject("ImportedDpkrReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ListByManyApartmentsHousesOverhaul {
            get {
                object obj = ResourceManager.GetObject("ListByManyApartmentsHousesOverhaul", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] LongProgInfoByStructEl {
            get {
                object obj = ResourceManager.GetObject("LongProgInfoByStructEl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] LongProgramByTypeWork {
            get {
                object obj = ResourceManager.GetObject("LongProgramByTypeWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] LongProgramReport {
            get {
                object obj = ResourceManager.GetObject("LongProgramReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] LongtermProgOverhaulInfo {
            get {
                object obj = ResourceManager.GetObject("LongtermProgOverhaulInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] MarginalCostKr1LivingSpace {
            get {
                object obj = ResourceManager.GetObject("MarginalCostKr1LivingSpace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NotIncludedWorksInProgram {
            get {
                object obj = ResourceManager.GetObject("NotIncludedWorksInProgram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OverhaulMkdIndicators {
            get {
                object obj = ResourceManager.GetObject("OverhaulMkdIndicators", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PlanOwnerCollectionReport {
            get {
                object obj = ResourceManager.GetObject("PlanOwnerCollectionReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] printform {
            get {
                object obj = ResourceManager.GetObject("printform", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ProgramVersion {
            get {
                object obj = ResourceManager.GetObject("ProgramVersion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishedDpkr {
            get {
                object obj = ResourceManager.GetObject("PublishedDpkr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishedDpkrExtended {
            get {
                object obj = ResourceManager.GetObject("PublishedDpkrExtended", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishedDpkrForSigned {
            get {
                object obj = ResourceManager.GetObject("PublishedDpkrForSigned", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishProgramByStructEl {
            get {
                object obj = ResourceManager.GetObject("PublishProgramByStructEl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishProgramByWork {
            get {
                object obj = ResourceManager.GetObject("PublishProgramByWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishProgramByWorkAndAddress {
            get {
                object obj = ResourceManager.GetObject("PublishProgramByWorkAndAddress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PublishProgramPeriodByWork {
            get {
                object obj = ResourceManager.GetObject("PublishProgramPeriodByWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RealitiesOutOfDpkr {
            get {
                object obj = ResourceManager.GetObject("RealitiesOutOfDpkr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ReasonableRate {
            get {
                object obj = ResourceManager.GetObject("ReasonableRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RegisterMkdToBeRepaired {
            get {
                object obj = ResourceManager.GetObject("RegisterMkdToBeRepaired", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RoomAreaControl {
            get {
                object obj = ResourceManager.GetObject("RoomAreaControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SpecialAccountDecision {
            get {
                object obj = ResourceManager.GetObject("SpecialAccountDecision", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StructElementList {
            get {
                object obj = ResourceManager.GetObject("StructElementList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Subsidy {
            get {
                object obj = ResourceManager.GetObject("Subsidy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SubsidyBudget {
            get {
                object obj = ResourceManager.GetObject("SubsidyBudget", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SubsidyBudgetSourcesFinancing {
            get {
                object obj = ResourceManager.GetObject("SubsidyBudgetSourcesFinancing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SubsidyInfo {
            get {
                object obj = ResourceManager.GetObject("SubsidyInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SummaryCharacteristicsOfHouse {
            get {
                object obj = ResourceManager.GetObject("SummaryCharacteristicsOfHouse", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
