Ext.define('B4.model.ProtocolGji', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'Protocol'
    },
    fields: [
        { name: 'Inspection', defaultValue: null },
        { name: 'Executant', defaultValue: null },
        { name: 'Contragent', defaultValue: null },
        { name: 'PhysicalPerson' },
        { name: 'PhysicalPersonInfo' },
        { name: 'DateToCourt' },
        { name: 'ToCourt', defaultValue: false },
        { name: 'Description' },
        { name: 'ViolationsList', defaultValue: null },
        { name: 'ParentDocumentsList' },
        { name: 'TypeDocumentGji', defaultValue: 60 },
        { name: 'ContragentName' },
        { name: 'TypeExecutant' },
        { name: 'MunicipalityNames' },
        { name: 'ZonalInspection', defaultValue: null },
        { name: 'CountViolation' },
        { name: 'PhysicalPersonPosition' },
        { name: 'DocumentNumber' },
        { name: 'ComissionDocumentDecision', defaultValue: 0 },        
        { name: 'DocumentDate' },
        { name: 'ComissionMeeting', defaultValue: null },
        { name: 'InspectorNames' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'TypeBase', defaultValue: null },
        { name: 'ResolutionId' },
        { name: 'ControlType' },
        { name: 'MoSettlement' },
        { name: 'UIN' },
        { name: 'PlaceName' },
        { name: 'CaseNumber' },
        { name: 'ViolatorFio' },
        { name: 'PlaceResidenceOutState' },
        { name: 'ActuallyResidenceOutState' },
        { name: 'IsPlaceResidenceOutState', defaultValue: false },
        { name: 'IsActuallyResidenceOutState', defaultValue: false },
        { name: 'ArticleLaw' },
        { name: 'InspectorPosition' }
    ]
});