Ext.define('B4.model.dict.ZonalInspection', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'ZonalInspection'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'Name' },
        { name: 'ZoneName' },
        { name: 'BlankName' },
        { name: 'DepartmentCode' },
        { name: 'ShortName' },
        { name: 'Address' },
        { name: 'Phone' },
        { name: 'IsNotGZHI', defaultValue: false },
        { name: 'Email' },
        { name: 'NameSecond' },
        { name: 'ZoneNameSecond' },
        { name: 'BlankNameSecond' },
        { name: 'ShortNameSecond' },
        { name: 'AddressSecond' },
        { name: 'Okato' },
        { name: 'NameGenetive' },
        { name: 'NameDative' },
        { name: 'NameAccusative' },
        { name: 'NameAblative' },
        { name: 'NamePrepositional' },
        { name: 'ShortNameGenetive' },
        { name: 'ShortNameDative' },
        { name: 'ShortNameAccusative' },
        { name: 'ShortNameAblative' },
        { name: 'ShortNamePrepositional' },
        { name: 'IndexOfGji' },
        { name: 'AppealCode' },
        { name: 'Oktmo' },
        { name: 'Locality' },
        { name: 'bik' },
        { name: 'inn' },
        { name: 'kbk' },
        { name: 'kpp' },
        { name: 'uin' },
        { name: 'ogrn' },
        { name: 'UFC' },
        { name: 'PersonalAcc' },
        { name: 'BankName' },
        { name: 'CorrespAcc' },
        { name: 'GisGmpId' }
    ]
});