Ext.define('B4.model.asfk.ASFK', {
    extend: 'B4.base.Model',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'ASFK'
    },
    fields: [
        { name: 'Id' },
        { name: 'NumVer'},
        { name: 'Former'},
        { name: 'FormVer'},
        { name: 'NormDoc' },
        { name: 'KodTofkFrom' },
        { name: 'NameTofkFrom' },
        { name: 'BudgetLevel' },
        { name: 'KodUbp' }, 
        { name: 'NameUbp' },
        { name: 'GuidVT' },
        { name: 'LsAdb' },
        { name: 'DateOtch' },
        { name: 'DateOld' },
        { name: 'VidOtch' },
        { name: 'KodTofkVT' },
        { name: 'NameTofkVT' },
        { name: 'KodUbpAdb' },
        { name: 'NameUbpAdb' },
        { name: 'KodGadb' },
        { name: 'NameGadb' }, 
        { name: 'NameBud' },
        { name: 'Oktmo' }, 
        { name: 'OkpoFo' },
        { name: 'NameFo' },
        { name: 'DolIsp' },
        { name: 'NameIsp' },
        { name: 'TelIsp' },
        { name: 'DatePod' },
        { name: 'SumInItogV' },
        { name: 'SumOutItogV' },
        { name: 'SumZachItogV' },
        { name: 'SumNOutItogV' },
        { name: 'SumNZachItogV' },
        { name: 'SumBeginIn' },
        { name: 'SumBeginOut' },
        { name: 'SumBeginZach' },
        { name: 'SumBeginNOut' },
        { name: 'SumBeginNZach' },
        { name: 'SumEndIn' },
        { name: 'SumEndOut' },
        { name: 'SumEndZach' },
        { name: 'SumEndNOut' },
        { name: 'SumEndNZach' },
        { name: 'DistributedSum' }
    ]
});