Ext.define('B4.model.ProtocolGji', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'Protocol'
    },
    fields: [
        { name: 'Inspection', defaultValue: null },
        { name: 'Executant', defaultValue: null },
        { name: 'Contragent', defaultValue: null },
        { name: 'PhysicalPerson' },
        { name: 'PhysicalPersonInfo' },
        { name: 'DateToCourt' },
        { name: 'ToCourt', defaultValue: false },
        { name: 'Description' },
        { name: 'ViolationsList', defaultValue: null },
        { name: 'ParentDocumentsList' },
        { name: 'TypeDocumentGji', defaultValue: 60 },
        { name: 'ContragentName' },
        { name: 'TypeExecutant' },
        { name: 'MunicipalityNames' },
        { name: 'PhysicalPersonPosition' },
        { name: 'CountViolation' },
        { name: 'DocumentNumber' },
        { name: 'DocumentDate' },
        { name: 'DateBirth' },
        { name: 'BirthPlace' },
        { name: 'ControlType' },
        { name: 'InspectorNames' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'TypeBase', defaultValue: null },
        { name: 'ResolutionId' },
        { name: 'DateOfProceedings' },
        { name: 'HourOfProceedings' },
        { name: 'MinuteOfProceedings' },
        { name: 'FormatDate' },
        { name: 'NotifNumber' },
        { name: 'ProceedingsPlace' },
        { name: 'Remarks' },
        { name: 'PersonRegistrationAddress' },
        { name: 'PersonFactAddress' },
        { name: 'PersonJob' },
        { name: 'PersonPosition' },
        { name: 'PersonBirthDatePlace' },
        { name: 'PersonDoc' },
        { name: 'PersonSalary' },
        { name: 'PersonRelationship' },
        { name: 'FormatPlace' },
        { name: 'FormatHour' },
        { name: 'FormatMinute' },
        { name: 'TypePresence' },
        { name: 'Representative' },
        { name: 'ReasonTypeRequisites' },
        { name: 'NotifDeliveredThroughOffice' },
        { name: 'ProceedingCopyNum' },
        { name: 'DateOfViolation' },
        { name: 'HourOfViolation' },
        { name: 'MinuteOfViolation' },
        { name: 'ResolveViolationClaim' },
        { name: 'NormativeDoc' },
        { name: 'MoSettlement' },
        { name: 'PlaceName' },
        { name: 'UIN' },
        { name: 'PhysicalPersonDocumentNumber' },
        { name: 'PhysicalPersonIsNotRF', defaultValue: false },
        { name: 'PhysicalPersonDocumentSerial' },
        { name: 'PhysicalPersonDocType' },
        { name: 'ComissionDocumentDecision', defaultValue: 0 },       
        { name: 'ComissionMeeting', defaultValue: null },
        { name: 'ArticleLaw' },
        { name: 'HasResolution' },
        { name: 'FiasPlaceAddress' },
        { name: 'MessageCheck', defaultValue: 0 },
        { name: 'TypeAddress', defaultValue: 0 },
        { name: 'PlaceOffense', defaultValue: 0 },
        { name: 'JudSector' },
        { name: 'AddressPlace' },
        { name: 'CaseNumber' },
        { name: 'ViolatorFio' },
        { name: 'ZonalInspection', defaultValue: null },
        { name: 'PlaceResidence' },
        { name: 'ActuallyResidence' },
        { name: 'PlaceResidenceOutState' },
        { name: 'ActuallyResidenceOutState' },
        { name: 'IsPlaceResidenceOutState', defaultValue: false },
        { name: 'IsActuallyResidenceOutState', defaultValue: false },
        { name: 'DateViolation' },
        { name: 'InspectorPosition' },
        { name: 'JudSectorName' },
        { name: 'Penalty' },
        { name: 'ChargeAmount' },
        { name: 'PaidAmount' },
        { name: 'IsFineCharged' },
        { name: 'FineChargeDate' },
        { name: 'CourtCaseNumber' },
        { name: 'CourtCaseDate' },
        { name: 'CourtSanction' }
    ]
});